# Generated by Django 5.0.1 on 2024-01-31 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translation',
            name='source_lang',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='target_lang',
        ),
        migrations.AddField(
            model_name='translation',
            name='source_language_slug',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='translation',
            name='target_language_slug',
            field=models.CharField(default='', max_length=5),
        ),
    ]
