# Generated by Django 5.0.1 on 2024-01-31 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translator_app', '0002_remove_translation_source_lang_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='translation',
            options={'ordering': ['-id']},
        ),
    ]
