# Generated by Django 5.0.1 on 2024-01-31 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translator_app', '0004_rename_target_text_translation_translated_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translation',
            old_name='source_language_slug',
            new_name='source_lang_slug',
        ),
        migrations.RenameField(
            model_name='translation',
            old_name='target_language_slug',
            new_name='target_lang_slug',
        ),
    ]
